export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const RENAME_CARD = 'RENAME_CARD';
export const CHANGE_CARD_DESCRIPTION = 'CHANGE_CARD_DESCRIPTION';

export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const CHANGE_COMMENT_VALUE = 'CHANGE_COMMENT_VALUE';

export const RENAME_COLUMN = 'RENAME_COLUMN';

export const USER_EXIT = 'USER_EXIT';
export const AUTH_ENTER = 'AUTH_ENTER';
export const NO_AUTH_ENTER = 'NO_AUTH_ENTER';